### ISSUE TITLE
contact 변환 파일 저장 경로 질문

### ISSUE THREAD

**Issue by aFewThings** [namhokim/cocoa_app#44]
안녕하세요
혹시 contact로 변환한 파일은 어디에 저장되는건가요?

**Comment by namhokim** [comment]
질문의 의미가 이해가 되지 않네요.
파일은 그 위치 그대로에 있습니다.
그 이유는 파일의 내용을 바꾸는 프로그램이 아니고 파일의 이름을 바꾸는 것이기 때문입니다.

예로 데스크탑에 a.txt 를 b.txt 로 바꾸면 그 파일은 데스크탑에 그대로 남아 있겠지요.

**Comment by aFewThings** [comment]
아, 제가 프로그램으로 테스트해봤는데 여전히 윈도우에서 자소 분리 현상이 일어나서 착각했네요. 

'무제.docx' 라는 파일을 mac에서 만들고 contact에 drag drop으로 변환했습니다. 
그리고 파일을 mail 앱을 통해 첨부하는 방식으로 다시 윈도우에서 파일을 다운로드했는데, 
'ㅁㅜㅈㅔ.docx'와 같이 자소분리 현상이 남아있습니다. 
제가 @namhokim 님께서 작성하신 다른 글을 읽지 못해서 올바른 사용법을 모르는 것일 수 있는데 
지금 절차에 문제되는 부분이 있을까요?

**Comment by namhokim** [comment]
절차는 맞습니다.
다만 경험상 외장드라이브에 있는 파일을 합쳐진 형태로 바꾸는 것이 동작하지 않음을 알고 있습니다.
혹시 그런 경우라면 내장 디스크로 파일을 복사하고 Contact를 적용해보심을 권장드립니다.

또한 한 번 이름을 바꾸었다고 하더라도 워드 등에서 저장을 하면 원래의 형태로 다시 이름이 풀릴 수 있습니다. 따라서 외부로 이동하기 바로 전에 수행을 하시는 것이 좋습니다.

**Comment by aFewThings** [comment]
일단은 말씀하신 내용에는 해당사항이 없었습니다. 
정확한 절차를 말씀드리면 파일을 내장 드라이브의 데스크탑에 위치시키고 Contact를 열어 드래그 드랍했고, done 메시지 이후에는 파일을 열거나 수정하지 않았습니다. 이어서 mail app을 통해 윈도우에서 다운받았습니다. 

드래그 드랍말고 'open'을 사용해보아도 동일한 것 같습니다. 
관련이 있을지는 모르겠으나 Macbook air m1 으로 테스트했습니다.

**Comment by namhokim** [comment]
iTerm 등 일부 애플리케이션을 이용하면 현재 파일의 이름이 풀려서 되어 있는지 여부를 확인 할 수 있습니다.
https://namocom.tistory.com/903 글위 데모 동영상 중에 해당 풀려있는지 여부를 표시하는 영상이 있으니 참고하세요.

**Comment by aFewThings** [comment]
확인하니 NFC로 변환되는건 맞는 것 같네요. 아무래도 전송과정에 다른 문제가 있었나봅니다. 
감사합니다.
