### ISSUE TITLE
타겟 날짜를 오늘 날짜로 setting 하는 기능 요청드립니다.

### ISSUE THREAD

**Issue by wookeeda** [namhokim/cocoa_app#6]
배경
- 매일 날짜를 직접 수정해서 getContent해야함.

요청내용
- 매일 당일로 자동 셋팅해주는 기능
  추가로  오늘로 셋팅되는 'today' 버튼도 있으면 좋을 것 같습니다

**Comment by namhokim** [comment]
현재 애플리케이션이 실행되면 당일 날짜로 표시하고 있습니다.
따라서 today 버튼으로 구현하는 것이 좋을 것 같다는 생각입니다.
날짜가 바뀌었을 때 자동으로 바꾸는 기능도 생각해볼 수는 있으나 날짜 변경 이벤트 감지를 해서 복잡해질 수 있어서 위의 기능 정도면 큰 피처가 아닐 것 같습니다.

**Comment by namhokim** [comment]
Solved at [v1.2.2](https://github.com/namhokim/cocoa_app/releases/tag/v1.2.2)
